[project]
name = "git-citations2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Frédéric LURET", email = "frederic.luret@univ-tours.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "pyfiglet>=1.0.4",
    "rich>=15.0.0",
]

[project.scripts]
git-citations2 = "git_citations2:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
